### ISSUE TITLE
estado del proyecto

### ISSUE THREAD

**Issue by hjf** [gbisheimer/x28_sniffer#1]
continuaste el desarrollo de este proyecto ? 
intente usarlo con mi alarma, pero no tuve mucho exito tratando de encontrar los codigos. 

parece que hay codigos que se envian muy rapido y el arduino no alcanza a decodificarlos, o puede que haya algun problema con los parametros. 

pude sacar (creo) algun que otro codigo, por ej 0x8046 parece ser "desactivada"  y 0x80dc parece ser "cambio estoy/me voy"

**Comment by gbisheimer** [comment]
Solo un poco más, pero ni sé donde habré dejado el código. Por las dudas te aclaro que yo estaba probando con una de las centrales X28 viejas modelo 9004-MPX. Para meterme en el bus MPX usé un sensor PIR que tenía dañado y le conecté el Arduino directamente ahí usando el regulador de 5V que ya trae el sensor:

![DSC07344](https://github.com/gbisheimer/x28_sniffer/assets/3077123/291ef3de-d606-48e0-9108-4614e6e1eb9c)

Te paso lo que pude relevar de las capturas de datos. Recuerdo que lo que me quedó por definir es cómo calcular el checksum de cada paquete.

```
// 1 bit: Paridad par
// 3 bits: ID?
// 8 bits: Comando
// 4 bits: Checksum??? Complementa la paridad?

1 000 00000001 0011 // Tecla 1
1 000 00000010 0101 // Tecla 2
0 000 00000011 0110 // Tecla 3
1 000 00000100 0110 // Tecla 4
0 000 00000101 0101 // Tecla 5
0 000 00000110 0011 // Tecla 6
1 000 00000111 0000 // Tecla 7
1 000 00001000 1001 // Tecla 8
0 000 00001001 1010 // Tecla 9
0 000 00001010 1100 // Tecla 10
0 000 00000000 0000 // Tecla 0
1 000 00001011 1111 // Tecla F
```

Y estos son datos son de otro archivo que encontré en la carpeta, pero no tengo más datos:

```
comando teclado
1 000 00001101 1100
respuesta central
0 100 10111110 1000
0 100 00000010 1010
1 100 00011000 1100
0 100 10100011 1110

comando teclado
1 000 00001101 1100
respuesta central
1 100 10111010 1110
1 100 00001001 0101
0 100 00011010 1001

central
0 011 10000000 1000
1 000 10100110 0100
1 100 00001001 0101
0 100 00011010 1001
1 100 10010010 1011


Central
0 100 10100011 1110
1 100 10111010 1110
1 100 11000000 0011
0 011 00000000 0011
0 011 10000000 1000

1 010 11000010 0111
1 010 11000001 0001
1 010 11000010 0111
1 010 11000001 0001
1 010 11000010 0111
1 010 11000001 0001
1 010 11000010 0111
1 010 11000001 0001
1 010 11000010 0111
0 001 01100001 0101
1 010 11000001 0001
0 001 01100001 0101
0 001 01100010 0011
```

Si podés compartir lo que estuviste haciendo, estaría bueno.

Saludos!

**Comment by hjf** [comment]
voy a intentar de nuevo mas tarde y subo los resultados. la que yo tengo es la 9004W-MPX, o sea la misma pero con el modulo inalambrico. 

de cualquier manera estaba pensando que el tema del checksum no es estrictamente necesario. basicamente lo unico que podemos hacer con estas centrales es replay y para eso con capturar las tramas sobra, ya que no es interactivo. son solo comandos fire and forget. 

mi objetivo es controlar la alarma por HA, al menos activar/desactivar/panico pero si se puede extraer los estados de las zonas tambien estaria bueno.

**Comment by gbisheimer** [comment]
Si, lo del checksum se puede obviar si relevas los códigos de todas las teclas. Hay que ver si en todos los modos los códigos de las teclas siempre se mantienen iguales. No se si serán los mismos si estás configurando las zonas que si estás visualizando el estado.

Yo también empecé este proyecto para conectar la central a mi HA! pero quedó trunco.

Tenía unas capturas del osciloscopio donde podía ver lo que yo mandaba y lo que me mandaba la central como respuesta. Si las las encuentro te las comparto.

**Comment by hjf** [comment]
al final termine sacando la libreria rcswitch porque no pude hacerla andar (se complica despues porque con esta libreria seria relativamente facil de implementar con ESPHome)

tambien estuve haciendo un poco de ing inversa:

teclas simples, modo normal:
codigo tecla

0000 0
8013 1
8025 2
0036 3
8046 4
0055 5
0063 6
8070 7
8089 8
009A 9
00AC P
80BF F
00CF ver tecla Z
80DC M
80EA 🔔
00F9 🔥

press largo:
P: 00AC 810A
F: 80BF 813C
🔥: 00F9 0119
🔔: 80EA 012F

TECLA Z:
00CF 0000: entrar en modo inclusion
00CF 8169: salir modo inclusion

---

respuestas alarma:
enviar 99 (armar)
6c28
49c1 -> cambia a "activada"

enviar codigo desact:
6819
c92b -> cambia a "desactivada"

estoy -> me voy: (z1 puerta abierta)
cbae c095 41a9 c91d

0xcbae -> cambia led a "me voy" 

[0000452297]: > 0x80DC - 0 6 d 8
[0000452384]: < 0xCBAE - 0 7 ba c
[0000452471]: < 0xC095 - 1 2 9 c
[0000452558]: < 0x41A9 - 1 4 1a 4
[0000452644]: < 0xC91D - 1 6 91 c

0000048421]: > 0x80DC - 0 6 d 8
[0000048507]: < 0xCBAE - 0 7 ba c
[0000048594]: < 0xC095 - 1 2 9 c
[0000048681]: < 0x41A9 - 1 4 1a 4

me voy -> estoy: (z1 puerta abierta)
4be8 402a c18c 490e
0x4be8 -> cambia led a "Estoy"

[0000484677]: > 0x80DC - 0 6 d 8
[0000484763]: < 0x4BE8 - 0 4 be 4
[0000484849]: < 0x402A - 0 5 2 4
[0000484936]: < 0xC18C - 0 6 18 c
[0000485022]: < 0x490E - 0 7 90 4

abrir puerta con sensor inalambrico, z1:
[0000071727]: < 0xCC03 - 1 1 c0 c
[0000072222]: < 0x1212 - 0 1 21 1 -> parece ser apertura
[0000072309]: < 0xB08A - 0 5 8 b
[0000072396]: < 0xC91D - 1 6 91 c
[0000072728]: < 0xAC44 - 0 2 c4 a

cerrar puertacon seonsor inalambrico, z1:
[0000115115]: < 0x9419 - 1 4 41 9 -> parece ser cierre
[0000115202]: < 0x3003 - 1 1 0 3
[0000115288]: < 0xC92B - 1 5 92 c

comportamiento de apertura, z1 (remoto 315mhz)
la alarma parece tener un contador de aperturas, como todos los sensores envian:
0x1212 para indicar apertura, si se envia 2 veces, la alarma espera que se envie
0x9419 para indicar cierre

si envio 2 veces 0x1212, pero una sola 0x9419, la alarma sigue considerando
la zona 1 como "abierta".

pero si mando mas veces 0x9419, la puerta queda cerrada (se ve que el codigo de la
alarma verifica los cierres y no hace underflow)

con alarma activada:

apertura puerta:
[0000232433]: < 0x1212 - 0  1  21  1
[0000232520]: < 0xB08A - 0  5   8  b 
[0000232606]: < 0x490E - 0  7  90  4

[0000359743]: < 0x1212 - 0  1  21  1
[0000359830]: < 0xE989 - 1  4  98  e
[0000359915]: < 0xB08A - 0  5   8  b -> hace prender led z1
[0000360003]: < 0xB881 - 1  0  88  b -> hace parpadear led z1 bajo/alto 
[0000360089]: < 0xCBFB - 1  5  bf  c
[0000360174]: < 0x4C8A - 0  5  c8  4
[0000360625]: < 0x49C1 - 1  0  9c  4



periodicamente:
ac44 -> todo el tiempo, no se que es

0x3808 -> hizo apagar leds zonas, parece indicar estado zonas

**Comment by hjf** [comment]
Hice un nuevo proyecto con lo aprendido en este, facil de integrar a HA con ESPHome, te dejo la URL por si lo queres probar: https://github.com/hjf/esphome-x28

**Comment by fedapon** [comment]
Hola @hjf y @gbisheimer!!
Se que hace tiempo que el post está inactivo, pero les cuento que con toda la info que recopilaron haciendo ingeniería inversa, armé una librería lista para ser integrada a otros proyectos.
Entre las mejoras está la de un buffer circular para no perder paquetes y la generación de eventos o callbacks cuando llega algún paquete "importante" al módulo.
Les dejo el link por si aún están interesados: [https://github.com/fedapon/x28-mpx-controller](https://github.com/fedapon/x28-mpx-controller)

Aún falta descubrir cual es el código de que está sonando la alarma, pero creo que con tiempo va a aparecer :)

**Comment by Hamberthm** [comment]
Hola gente muy buen proyecto, consulta, por qué no se sabe el código de evento para "alarma disparada"? Quiero integrar esto en la alarma de casa para reemplazar el llamador telefónico en mi vieja X28, y este evento es el que más me interesa.

**Comment by hjf** [comment]
@Hamberthm es cuestión de ejecutar el sniffer y buscar cual es el código que genera la alarma para avisarle a los teclados (y supongo que a las sirenas MPX) que está sonando.

el problema es que cuando la alarma se dispara, la central manda un montón de mensajes.

habría que dumpear varios disparos de alarma, filtrar el ruido, y de lo que queda, hacer replay y ver si el teclado se pone en modo alarma (zona afectada parpadeando , que se resetea con F44)

yo lo terminé implementando como un GPIO porque en definitiva, como lo tengo integrado a Home Assistant con un ESP32, tengo GPIO de sobra. y la ventaja es que es más confiable ponele, porque un mensaje MPX se puede llegar a perder pero el GPIO imposible.

creo que la mayoría lo está haciendo de esa manera

**Comment by Hamberthm** [comment]
> @Hamberthm es cuestión de ejecutar el sniffer y buscar cual es el código que genera la alarma para avisarle a los teclados (y supongo que a las sirenas MPX) que está sonando.
> 
> el problema es que cuando la alarma se dispara, la central manda un montón de mensajes.
> 
> habría que dumpear varios disparos de alarma, filtrar el ruido, y de lo que queda, hacer replay y ver si el teclado se pone en modo alarma (zona afectada parpadeando , que se resetea con F44)
> 
> yo lo terminé implementando como un GPIO porque en definitiva, como lo tengo integrado a Home Assistant con un ESP32, tengo GPIO de sobra. y la ventaja es que es más confiable ponele, porque un mensaje MPX se puede llegar a perder pero el GPIO imposible.
> 
> creo que la mayoría lo está haciendo de esa manera 

Mil gracias por la explicación!! Supongo que con GPIO te referís a los que tiene la alarma que los podés programar para que cambien de estado en caso de disparo? Es asi?

**Comment by hjf** [comment]
> Mil gracias por la explicación!! Supongo que con GPIO te referís a los que tiene la alarma que los podés programar para que cambien de estado en caso de disparo? Es asi?

por GPIO me refiero a los del microcontrolador.

yo directamente agarre del mismo cable dónde sale los 12V para la sirena, y después le puse un divisor resistivo para bajar de 12 a 3.3V, y lo conecte a uno de estos pines. luego los voy leyendo y si cambian de estado, el ESP32 manda una notificación a home Assistant 

después, en HA tengo una scene que enciende todas las luces exteriores de la casa, que se dispara tras la notificación del ESP. esto con suerte haría que las cámaras, que graban por movimiento, empiecen a grabar al detectar el cambio de luz.

**Comment by Hamberthm** [comment]
>  
> > Mil gracias por la explicación!! Supongo que con GPIO te referís a los que tiene la alarma que los podés programar para que cambien de estado en caso de disparo? Es asi?
> 
> por GPIO me refiero a los del microcontrolador.
> 
> yo directamente agarre del mismo cable dónde sale los 12V para la sirena, y después le puse un divisor resistivo para bajar de 12 a 3.3V, y lo conecte a uno de estos pines. luego los voy leyendo y si cambian de estado, el ESP32 manda una notificación a home Assistant 
> 
> después, en HA tengo una scene que enciende todas las luces exteriores de la casa, que se dispara tras la notificación del ESP. esto con suerte haría que las cámaras, que graban por movimiento, empiecen a grabar al detectar el cambio de luz.

Ahora si, entendido al 100. Gracias de nuevo! Voy a ir por algo similar y comento como me fue.
